<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
      
                      <h1 class="page-header">
                              Java Tutorials for beginners <small>Series</small>
                          </h1>
      
                      <!-- Third Blog Post -->
                      <h2>
                              <a href="#">Java program to find the largest and smallest
                                  number in a ArrayList </a>
                          </h2>
                      <p class="lead">
                          by <a href="#">Anil Chauhan</a>
                      </p>
                      <p>
                          <span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:45 PM
                      </p>
                      <hr>
                      <img class="img-responsive" src="resources/images/Arraylist.jpg" alt="">
                      <h1> Java program to find the largest and smallest number in a list</h1>
      
      
                      <hr>
      
                      <div>
      
                          <div dir="ltr" style="text-align: left;" trbidi="on">
      
                              <h4 style="text-align: left;">Hello everybody, this is a Java program which finds out the smallest and largest number&nbsp;in the ArrayList.</h4>
          <h4 style="text-align: left;">
          </h4>
          <h4 style="text-align: left;">
          Here we use 2 predefined functions min() and max() from Collections Class which&nbsp;check for the smallest and largest number&nbsp;in a <a href="http://programminginpython.com/category/programs-on-lists/" target="_blank">ArrayList </a>respectively.</h4>
          
                              <h3 style="text-align: left;">&nbsp;</h3>
                              <h3 style="text-align: left;">
          <span style="color: #dd9933;">Task</span> :</h3>
                              <h4 style="text-align: left;">
          To find largest and smallest number&nbsp;in a list.</h4>
                              <h4>
          <span style="color: #dd9933;">Approach</span> :</h4>
                              <h4>
          </h4>
                              <div class="separator" style="clear: both; text-align: center;">
                              </div>
                              <ul style="text-align: left;">
                                  <li>
                                      <h4 itemprop="name">
          Generating random integers from a Random Class&nbsp;</h4>
                                      <h4 itemprop="name">
          </h4>
                                  </li>
                                  <li>
                                      <h4>
          Initialise an empty ArrayList</h4>
                                  </li>
                                  <li style="width: 490px; ">
                                      <h4>
          generate and store integer in ArrayList using a for loop<code></code>.</h4>
                                  </li>
                                  <li>
                                      <h4>
          In the for loop add each number to the Arraylist.</h4>
                                  </li>
                                  <li>
                                      <h4>
          Now we use predefined&nbsp; method <code>max()</code> from Collections class&nbsp; find the largest element in a list.</h4>
                                  </li>
                                  <li>
                                      <h4>
          Similarly we use another predefined methods&nbsp; <code>min()</code> to find the smallest element in a ArrayList list.</h4></li>
      
     <h4><a href="https://3.bp.blogspot.com/-WSIVaRFoUWU/V-BjIV_qViI/AAAAAAAAABk/SVsIkstfCbEYd9NpJVSknYYsWzvAcO16gCLcB/s1600/2016-09-21_3-02-38.png" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" height="158" src="https://3.bp.blogspot.com/-WSIVaRFoUWU/V-BjIV_qViI/AAAAAAAAABk/SVsIkstfCbEYd9NpJVSknYYsWzvAcO16gCLcB/s640/2016-09-21_3-02-38.png" width="640" style="width: 452px; "/></a></h4>
      
         <li><h4> <b>after running above code you will&nbsp; get a Arraylist full of 1000 elements&nbsp; generated by random&nbsp;</b><b>number </b></h4>
          </li>
                                  &nbsp;
                                  <div class="separator" style="clear: both; text-align: center;">
                                      <a href="https://4.bp.blogspot.com/-IVrehjWeKT4/V-Bf6MNTkmI/AAAAAAAAABc/gkLBDmpwY0840AvN9kDORxLjlRpb3o1XwCEw/s1600/Capture.GIF" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" height="252" src="https://4.bp.blogspot.com/-IVrehjWeKT4/V-Bf6MNTkmI/AAAAAAAAABc/gkLBDmpwY0840AvN9kDORxLjlRpb3o1XwCEw/s400/Capture.GIF" width="400" />
                                      </a>
                                  </div>
                                  <div class="separator" style="clear: both; text-align: center;">
                                  </div>
                                  <div class="separator" style="clear: both; text-align: center;">
                                  </div>
                              </ul>
                              <h4 style="text-align: left;">
          <b>&nbsp;we will use collection class max and min method to find maximum value and minimum value&nbsp; in the ArrayList&nbsp; after that we will sort&nbsp; Arraylist by help of Collection class sort method&nbsp;</b></h4>
                              <h4 style="text-align: left;">
          <b>&nbsp;</b></h4>
                              <div class="separator" style="clear: both; text-align: center;">
                                  <a href="https://3.bp.blogspot.com/-WSIVaRFoUWU/V-BjIV_qViI/AAAAAAAAABk/SVsIkstfCbEYd9NpJVSknYYsWzvAcO16gCLcB/s1600/2016-09-21_3-02-38.png" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" height="158" src="https://3.bp.blogspot.com/-WSIVaRFoUWU/V-BjIV_qViI/AAAAAAAAABk/SVsIkstfCbEYd9NpJVSknYYsWzvAcO16gCLcB/s640/2016-09-21_3-02-38.png" width="640" style="width: 449px; " />
                                  </a>
                              </div>
                              <h4 style="text-align: left;">
          <b>&nbsp;here is our max and min value</b></h4>
                              <h4 style="text-align: left; width: 395px">
          <b>&nbsp;</b></h4>
                              <h4 style="text-align: left;">
          <b>&nbsp;</b></h4>
                              <h4 style="text-align: left;">
          <b>&nbsp;</b></h4>
                              <h4 style="text-align: left;">
          <b>&nbsp;</b></h4>
                              <div class="separator" style="clear: both; text-align: center;">
                                  <a href="https://2.bp.blogspot.com/-zIo9GKKDFtA/V-BkBW-_HbI/AAAAAAAAABo/x8egOEoZbtoU8t9MqhQyRqKEmDbKRdWvACLcB/s1600/2016-09-21_3-05-07.png" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" height="251" src="https://2.bp.blogspot.com/-zIo9GKKDFtA/V-BkBW-_HbI/AAAAAAAAABo/x8egOEoZbtoU8t9MqhQyRqKEmDbKRdWvACLcB/s400/2016-09-21_3-05-07.png" width="400" />
                                  </a>
                              </div>
                              <br />
                              <br />
                              <br />
                              <br />
                              <br />
                              <br />
                              <div class="separator" style="clear: both; text-align: center;">
                                  <a href="https://1.bp.blogspot.com/-tD0v80ogcio/V-BkBuPXQUI/AAAAAAAAABs/3GmH_zfV6tsC4QohmRS8Ge7LcT33OoaHwCLcB/s1600/2016-09-21_3-06-24.png" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" height="251" src="https://1.bp.blogspot.com/-tD0v80ogcio/V-BkBuPXQUI/AAAAAAAAABs/3GmH_zfV6tsC4QohmRS8Ge7LcT33OoaHwCLcB/s400/2016-09-21_3-06-24.png" width="400" />
                                  </a>
                              </div>
                              <h4 style="text-align: left;">
          <b><br /></b></h4>
                              <h4 style="text-align: left;">
          <b>Source Code :&nbsp; </b></h4>
      
                              <pre>
      
          package com.anil.java_tutorials;
      
          import java.util.ArrayList;
          import java.util.Collections;
          import java.util.Random;
      
          public class Max_Min_find_ArrayList {
      
             
      
              public static void main(String[] args) {
                  ArrayList<Integer> mylist=new ArrayList<Integer>();
                  for  (int i=1;i<1000;i++){
                      Random ran=new Random();
                      mylist.add(ran.nextInt(100000000));
                     
                  }
                  int max=Collections.max(mylist);
                  int min=Collections.min(mylist);
                  Collections.sort(mylist);
                  System.out.println("");
                 
                 
              }
      
          }
          </pre>
      
                          </div>
      
                          <div id="SC_TBlock_188508" class="SC_TBlock">loading...</div>
      
                          <script type="text/javascript">
                              var SC_CId = "188508",
                                  SC_Domain = "n.ads1-adnow.com";
                              SC_Start_188508 = (new Date).getTime();
                          </script>
                          <script type="text/javascript" src="https://st-n.ads1-adnow.com/js/adv_out.js"></script>
      
      
                      </div>
      
                      <!-- Pager -->
                      <ul class="pager">
                          <li class="previous"><a href="#">&larr; Older</a>
                          </li>
                          <li class="next"><a href="#">Newer &rarr;</a>
                          </li>
                      </ul>
      
                  